deploy-frontend-prod-te-ka:
  stage: deploy
  image: node:15.11.0
  script:
    - npm install -g firebase-tools@9.7
    - firebase use prod --token "${FIREBASE_CI}"
    - firebase target:apply hosting te-ka-app te-ka-app --non-interactive
    - firebase deploy --only hosting:te-ka-app --non-interactive --token "${FIREBASE_CI}"
  when: manual
  cache:
    key: firebase-cache
    paths:
      - node_modules/
  only:
    refs:
      - master
    changes:
      - te-ka/**/*
      - ci/deploy/frontend/te-ka/.deploy_frontend_te_ka_prod.yml
      - .gitlab-ci.yml
