deploy-frontend-staging-te-fiti:
  stage: deploy
  image: node:15.11.0
  script:
    - npm install -g firebase-tools@9.7
    - firebase use staging --token "${FIREBASE_CI}"
    - firebase target:apply hosting te-fiti-staging-87104 te-fiti-staging-87104 --non-interactive
    - firebase deploy --only hosting:te-fiti-staging-87104 --non-interactive --token "${FIREBASE_CI}"
  cache:
    key: firebase-cache
    paths:
      - node_modules/
  only:
    refs:
      - staging
    changes:
      - te-fiti/**/*
      - ci/deploy/frontend/te-fiti/.deploy_frontend_te_fiti_staging.yml
      - .gitlab-ci.yml
