deploy-frontend-dev-te-fiti:
  stage: deploy
  image: node:15.11.0
  script:
    - npm install -g firebase-tools@9.7
    - firebase use dev --token "${FIREBASE_CI}"
    - firebase target:apply hosting te-fiti-dev-399d0 te-fiti-dev-399d0 --non-interactive
    - firebase deploy --only hosting:te-fiti-dev-399d0 --non-interactive --token "${FIREBASE_CI}"
  cache:
    key: firebase-cache
    paths:
      - node_modules/
  only:
    refs:
      - dev
    changes:
      - te-fiti/**/*
      - ci/deploy/frontend/te-fiti/.deploy_frontend_te_fiti_dev.yml
      - .gitlab-ci.yml
